---
title: "Fun"
output: 
  html_document: 
    theme: flatly
    highlight: monochrome
    keep_md: yes 
    # toc: true  
    # toc_depth: 6
    # toc_float: 
    #   collapsed: true 
    #   smooth_scroll: true
--- 

```{r, echo=FALSE, include=FALSE, message=FALSE, error=FALSE, warning=FALSE}

library(knitr)
library(rmarkdown)
library(here)
library(icons)
library(fontawesome)

```

<style>
#TOC {
  background: url("static/TOC.png");
  background-size: contain;
  padding-top: 80px !important;
  padding-bottom: 80px !important;
  background-repeat: no-repeat;
}
</style>

<style>
a:link {
    color: purple;
}

a:visited {
    color: purple;
}

 a:hover {
    color: purple;
}

hr {
  height: 1px;
  background-color: #999999;
  border: none;
    }

</style>


```{css, echo = FALSE}

@import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;1,400&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Bitter:wght@400&display=swap');

/* title of page */
.title {
  font-family: 'Bitter';
}

/* body of page */
body {
    font-family: 'Open Sans';
    font-size: 15px;
    background-color: #fbf9f7;
}

/* styling for headings in TOC */
h4, #TOC>ul>li {
  font-family: 'Montserrat';
}

h5, #TOC>ul>ul>li {
  font-family: 'Montserrat';
}



/* styling for headings on page */
h4 {
  font-family: 'Bitter';
  font-size: 23px;
  color: #853078;
}

h5 {
  font-family: 'Bitter';
  font-size: 20px;
}

.tocify {
  # position: -webkit-sticky;
  # position: sticky; 
  # top: 120px; /*Controls where TOC stops when sticky */
  width: 100% !important;
  border: none;
}


/* styling for TOC overall */
.list-group-item {
    color: #666666;
    font-size: 15px;
    background-color: #F7F3F0;
}

/* styling for active item selected in TOC */
.list-group-item.active {
    color: white;
    background-color: #853078;
    border: none;
}

/* styling for item/heading being hovered over in TOC */
.list-group-item:hover, 
.list-group-item.active:hover {
    color: #853078;
    background-color: white;
}


/*----------------NAVBAR ---------------*/
.navbar-default {
    background-color: #333333f2;
}

.navbar-default .navbar-nav>.open>a, 
.navbar-default .navbar-nav>.active>a, 
a.dropdown-toggle:hover {
  background-color: #333333 !important;
}

/* Dropdown menu color */
.navbar-default .dropdown-menu {
  background-color: #333333;
}

/* Dropdown menu hover color */
  .navbar-default .dropdown-menu>li>a:hover {
    background-color: #333333f2;
  }

/* Navbar Links when hovered*/
.navbar-default .dropdown-menu>.active>a
.navbar-default .navbar-nav>.active>a:hover, 
.navbar-default .navbar-nav:hover, 
.navbar-default .navbar-nav>li>a:hover, 
a.navbar-brand:hover {
  color: #ffffffab !important;
  background-color: #333333;
}
```

***  

**Interests**:  

`r fa("chess-queen", fill = "black")`  I love to play board games  
`r fa("chess-queen", fill = "white")` I was an inter-school chess champion, and placed 3rd when I was 12 years old, in the Girls 16-18 category  

`r fa("guitar", fill = "black")` I occasionally play the ukulele  
`r fa("guitar", fill = "white")` I was also the lead drummer in my school's marching band  

`r fa("utensils", fill = "black")` I try to learn a new recipe every week  
`r fa("utensils", fill = "white")` Some of my most made recipes include coq au vin blanc, [kheema](https://www.indianhealthyrecipes.com/keema-recipe-mutton-keema-curry/), and mushroom risotto  

`r fa("book", fill = "black")` I love reading    
`r fa("book", fill = "white")` I try to read at least one book per month    
`r fa("book", fill = "white")` Some of my all time favourite reads include [Pride and Prejudice](https://www.goodreads.com/book/show/1885.Pride_and_Prejudice?ac=1&from_search=true&qid=wJPVLiJ8gY&rank=1), [Becoming](https://www.goodreads.com/book/show/38746485-becoming?ac=1&from_search=true&qid=IcUQ5yKVD8&rank=1), [Talking to Strangers](https://www.goodreads.com/book/show/43848929-talking-to-strangers?ac=1&from_search=true&qid=LFr6PNDNHS&rank=2), [The Five People You Meet in Heaven](https://www.goodreads.com/book/show/3431.The_Five_People_You_Meet_in_Heaven?ac=1&from_search=true&qid=Wr6kgBcu6B&rank=1), and [The Genetic Lottery: Why DNA Matters for Social Equality](https://www.goodreads.com/book/show/57423806-the-genetic-lottery?ac=1&from_search=true&qid=BhUqC0woxR&rank=2)   

`r fa("xbox", fill = "black")` I'm Team Xbox  
`r fa("xbox", fill = "white")` Some of my favourites include the Assassin's Creed series, Watch Dogs: Legion     

 <br>

**Skills**:  

`r fa("bell-concierge", fill = "black")` I was the Head Server at a [well-known restaurant](https://www.mumbailocal.ca/) in Downtown Vancouver  
`r fa("bell-concierge", fill = "white")` Several customers made reservations specifically during my work shift, wanting to experience my hospitality (they told me so!)




<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>


